[package]
name = "ngc"
version = "0.1.0"
description = "New Generation 5G Core"
authors = ["VPlane Telecoms"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "apps/smf",
    "apps/upf",
]
