# [log]
# level = "info"

# [smf]
# dns = [
#   "8.8.8.8",
#   "8.8.4.4",
#   "2001:4860:4860::8888",
#   "2001:4860:4860::8844"
# ]

# [[smf.sbi]]
# addr = "127.0.0.4"
# port = 7_777

# [[smf.pfcp]]
# address = "127.0.0.4"
# ipv6-address = "::1"

# [[smf.gtpc]]
# address = "127.0.0.4"
# ipv6-address = "::1"

# [[smf.gtpu]]
# address = "127.0.0.4"
# ipv6-address = "::1"

# [[nrf.sbi]]
# address = "127.0.0.10"
# ipv6-address = "::1"
# port = 7_777

# [[upf.pfcp]]
# address = "127.0.0.7"
